server:
  port: 8505

spring:
  application:
    name: merge-cluster

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cluster-eureka-server:8761/eureka/