server:
  port: 8503
spring:
  application:
    name: cluster-finder

merge:
  cluster:
    url: http://merge-cluster:8505/mergeCluster/merge/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cluster-eureka-server:8761/eureka/



