server:
  port: 8501
spring:
  application:
    name: data-parser

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cluster-eureka-server:8761/eureka/
